### ISSUE TITLE
https://sourceforge.net/projects/z-i/ status

### ISSUE THREAD

**Issue by pinanew** [anticensority/pac-script-generator#2]
Seems like not updated from 2020-09-15.
And
`panic: Negative status code: 404. For url: https://svn.code.sf.net/p/z-i/code-0/dump.csv`

**Comment by ilyaigpetrov** [comment]
@rnew, thanks for reporting. I'm a little bit curious: how and where do you use this generator?

**Comment by pinanew** [comment]
Вроде уже оффтоп, можно на русский перейти, я думаю.
Прямо сейчас немного модифицирую, чтобы генерить PAC файлы для себя локально. Видел разные решения, но они обычно на баше и/или питоне, и выглядят переусложнёными. Смешно, что я знаю баш и немного питон, а Го компилирую в первый раз, и всё равно эта прога выглядит проще всего.

**Comment by ilyaigpetrov** [comment]
Там у хрома есть лимит на размер скрипта в 1МБ, его только через
какое-нибудь расширение можно обойти. В настройках FireFox лимита нет, но у
них есть лимит на объём памяти (RAM).

**Comment by pinanew** [comment]
Про хром знаю, но я хром не использую. В фф вроде бы срабатывает, 5 427 709 байт съедает.

**Comment by ilyaigpetrov** [comment]
На всякий случай сообщаю, что ещё есть NodeJS: https://github.com/anticensority/pac-script-generator/tree/production, но я его более не поддерживаю.

**Comment by ilyaigpetrov** [comment]
For some reason after getting `https://svn.code.sf.net/p/zapret-info/code/dump.csv` and then trying to parse it throws `panic: unexpected EOF`. Not always but often. And I've never seen this error with dump.csv from GitHub repo, only with sf.net.
