### ISSUE TITLE
Remove custom domains from list

### ISSUE THREAD

**Issue by x100x-dev** [anticensority/pac-script-generator#5]
I see the option to **add** custom domains to the list.
Is there an option, on the contrary, to **remove**  domain/domains from the list?
Or specify domains that will not initially be added to the list?

**Comment by ilyaigpetrov** [comment]
See [ignoredHostnames](https://github.com/anticensority/pac-script-generator/blob/0c232047ac89a2c6c7eaf138102793ec66b1cc56/main.go#L153).
You should initialize it the same [way](https://github.com/anticensority/pac-script-generator/blob/0c232047ac89a2c6c7eaf138102793ec66b1cc56/main.go#L226C2-L226C17) as `customHostnames`:
```go
ignoredHostnames := map[string]bool{
  "www.youtube.com": true,
}
```
